### ISSUE TITLE
enabling virtualization in the BIOS for Windows 10 Home

### ISSUE THREAD

**Issue by brettdimond** [ubc-library-rc/intro-docker#5]
When following the documentation links provided in the workshop, I was not able to figure out how to enable virtualization on Windows 10 Home. As a result, in addition to (1) including separate documentation for installing Docker Desktop on Windows 10 Home, it might also be beneficial to (2) include within this section instructions on how to enable virtualization in the BIOS. The instructions I followed were https://thewebspark.com/2019/04/02/how-to-enable-virtualization-in-bios-of-windows-10-home-hp-systems-solved/. However, these are specific to HP systems, and my understanding is that the process will differ across systems.

**Comment by chiselinc** [comment]
This is kind of a hard one, because this is actually a problem _by design_ -  Microsoft wants people to purchase Pro, Education, or Enterprise for any functionality beyond basic tasks, hence the serious workaround to enable virtualization in Windows Home edition.

I'm adding some supporting links, and making the Hyper-V step for Pro, Education and Enterprise more clear in the module, but the "HP Systems-specific" element you've stumbled across is because each hardware manufacturer will have a different way to enable BIOS upon first booting the device. I'll include some coverage for that, but there's only so much we can coordinate for long-tail device specs in a module like this!

Thanks for all your feedback, as I passed along to the team through Eka, it's incredibly helpful as opposed to "look at your own curriculum and try to guess what's unclear" 🙂 Cheers!
